var mainHelp =
        "<h1>BelleChat Help</h1>"
        + "<p>The main screen of BelleChat is divided as follows (from top to bottom):"
        + "<ul><li><b>Tab Area</b> Each joined channel has a tab for incoming and outgoing messages, and there is also one for the server's output.</li>"
        + "<li><b>Message area</b> Messages are shown in this area. Any URLs in the message can be launched by clicking on them.</li>"
        + "<li><b>Input area</b> Type commands or messages in this box, and press Return, or the button at the right of the Input Area.</li>"
        + "</ul></br>"
        + "<h2>Toolbar</h2>"
        + "<p>From left to right:"
        + "<ul><li><b>Exit.</b></li>"
        + "<li><b>Connect</b> or <b>Disconnect</b> from the server.</li>"
        + "<li><b>Channels</b> Opens the Channel Menu.</li>"
        + "<li><b>Users</b> Opens the User Page.</li>"
        + "<li><b>More</b> Opens the More Menu.</li>"
        + "</ul></br>"
        + "<h2>Channel Menu</h2>"
        + "<ul><li><b>Join Channel...</b> Enter the name of the channel in the dialog. It must start with a hash (#). If the channel doesn't exist on the server, and the server allows it, it will be created for you.</li>"
        + "<li><b>Leave channel</b> Leave the currently selected channel.</li>"
        + "<li><b>List channels</b> Lists all the channels on the server, and shows their topics if available. Click on a channel to join it.</li>"
        + "</ul></br>"
        + "<h2>More Menu</h2>"
        + "<ul><li><b>Settings</b> Opens the Settings Page, which has three options:</li>"
        + "<ul><li><b>Server</b> Here you can change the server's settings.</li>"
        + "<li><b>Display</b> Here you can change various display-related settings, such as the colour of your messages.</li>"
        + "<li><b>User Info</b> Here you can enter some information about yourself, which can be viewed by some browsers. You can turn it off if you prefer.</li></ul>"
        + "<li><b>Help</b> Shows this page</li>"
        + "<li><b>About BelleChat</b> Shows the version and copyright information.</li>"
        + "</ul>"

var startPageText =
        "<h1>Before you start...</h1>"
        + "<p> Welcome to BelleChat, an Internet Relay Chat (IRC) client for Symbian smartphones. "
        + "<h2>Selecting a server</h2>"
        + "<p>You now need to choose a server to connect to, of which there are thousands throughout the world. A list of servers, and other IRC-related help, can be found at the <a href= \"http://www.irchelp.org/\">IRC help archives</a>."
        + "<h2>Now what?</h2>"
        + "<p>Now that you have the details of a server, you need to enter them on the Server Settings page. Click the OK icon to proceed to the Server settings page."
var serverHelp =
        "<h1>Server Settings</h1>"
        + "This is where you enter the server's settings. If you change any of these settings (except for nickname) whilst connected, "
        + "the changes won't take effect until you've disconnected and reconnected."
        + "<ul><li><b>Server</b> This is where you enter the URL of the chosen IRC server.</li>"
        + "<li><b>Port</b> This is the server's port. You don't normally need to change this.</li>"
        + "<li><b>Nickname</b> Enter your chosen nickname here. </li>"
        + "<li><b>Password & Username</b> If your server requires these details, enter them here. </li>"
        + "<li><b>Real name</b> Enter your real name here (if you want to...)</li>"
        + "<li><b>Default quit message</b> BelleChat will send the message entered here when you disconnect from the server.</li>"
        + "<li><b>Connection timeout</b> This is the time in seconds that BelleChat will wait for a connection before giving up. You might need to increase this if you have a slow connection.</li>"
        + "<li><b>Respond to IDENT request</b> If you switch this on, BelleChat will respond to an IDENT request from the server. This asks for the username of the client, which for BelleChat is whatever's in the Username box. "
        + "This only works if the server can connect to TCP port 113 on your phone. This requires a setting in your firewall, and doesn't always work if you're using a cellular connection. "
        + "Luckily most servers work without an IDENT response, so you can usually leave this off. </li>"
        + "<li><b>Join channels on connection</b> If you switch this on, BelleChat can automatically join one or more channels on connection. Enter each channel (followed by it's key if it's protected), separated by a comma. "
        + "For example: \"#wibble, #hatstand letmein\" will join #wibble and the protected channel #hatstand.</li></ul>"






